/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package graph;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

public class Library
{
    public static void main(String[] args)
    {
        System.out.println("\nNothing broke.");
    }
}
