/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linked.list;


public class Library {

    public static void main(String[] args)
    {
        ReverseLinkedList reverseLinkedList = new ReverseLinkedList();
        LinkedList linkedList1 = new LinkedList();
        linkedList1.append(1);
        linkedList1.append(2);
        linkedList1.append(3);
        linkedList1.append(4);
        linkedList1.append(5);

        System.out.println(linkedList1);
        System.out.println(reverseLinkedList.reverseLinkedListInPlace(linkedList1));
        System.out.println(reverseLinkedList.reverseLinkedListInPlace(linkedList1));


        LinkedList linkedList2 = new LinkedList();
        linkedList2.append(6);
        linkedList2.append(7);
        linkedList2.append(8);
        linkedList2.append(9);
        linkedList2.append(10);

        LinkedList linkedList3 = new LinkedList();
        linkedList3.append(11);
        linkedList3.append(12);
        linkedList3.append(13);
        linkedList3.append(14);
        linkedList3.append(15);



    }
}
